import os
import json
import re
import urllib.request
import urllib.parse
import urllib.error
from typing import List, Dict, Optional

# Primary Gemini models in order of preference & speed
GEMINI_MODELS = [
    "gemini-3-flash-preview",
    "gemini-3.6-flash",
    "gemini-3.1-flash-lite"
]

# Fast acronym & alias resolver for global cities
CITY_ALIASES = {
    "la": "Los Angeles",
    "lax": "Los Angeles",
    "nyc": "New York City",
    "ny": "New York City",
    "sf": "San Francisco",
    "sfo": "San Francisco",
    "dc": "Washington D.C.",
    "kl": "Kuala Lumpur",
    "hk": "Hong Kong",
    "rio": "Rio de Janeiro",
    "vegas": "Las Vegas",
    "delhi": "Delhi",
    "new delhi": "New Delhi",
    "bombay": "Mumbai",
    "mumbai": "Mumbai",
    "madras": "Chennai",
    "calcutta": "Kolkata",
    "bengaluru": "Bangalore"
}

# Major global cities fast-lookup dictionary
MAJOR_GLOBAL_CITIES = [
    "los angeles", "new york", "san francisco", "chicago", "houston",
    "miami", "seattle", "washington", "boston", "london", "manchester", "paris",
    "berlin", "rome", "madrid", "barcelona", "amsterdam", "brussels", "vienna",
    "zurich", "geneva", "dublin", "stockholm", "oslo", "copenhagen", "helsinki",
    "tokyo", "osaka", "kyoto", "seoul", "beijing", "shanghai", "guangzhou",
    "hong kong", "taipei", "bangkok", "singapore", "kuala lumpur", "jakarta",
    "manila", "hanoi", "ho chi minh", "delhi", "new delhi", "mumbai", "bangalore",
    "chennai", "kolkata", "hyderabad", "pune", "ahmedabad", "karachi", "lahore",
    "islamabad", "dhaka", "dubai", "abu dhabi", "riyadh", "doha", "cairo",
    "sydney", "melbourne", "brisbane", "auckland", "toronto", "vancouver",
    "montreal", "mexico city", "sao paulo", "rio de janeiro", "buenos aires",
    "johannesburg", "nairobi", "male", "kathmandu"
]


def clean_latex_formatting(text: str) -> str:
    r"""
    Sanitizes raw LaTeX mathematical notation generated by LLMs into clean, human-readable Unicode text.
    Transforms $\text{NO}_2$ -> NO₂, $\text{PM}_{2.5}$ -> PM2.5, $\mu\text{g/m}^3$ -> µg/m³, $102\text{ ppb}$ -> 102 ppb.
    """
    if not text:
        return ""

    # 1. Standard chemical formulas in LaTeX
    text = re.sub(r"\$\\text\{PM\}\_?\{?2\.5\}?\$|\$\\text\{PM2\.5\}\$", "PM2.5", text, flags=re.IGNORECASE)
    text = re.sub(r"\$\\text\{PM\}\_?\{?10\}?\$|\$\\text\{PM10\}\$", "PM10", text, flags=re.IGNORECASE)
    text = re.sub(r"\$\\text\{NO\}\_?\{?2\}?\$|\$\\text\{NO2\}\$", "NO₂", text, flags=re.IGNORECASE)
    text = re.sub(r"\$\\text\{O\}\_?\{?3\}?\$|\$\\text\{O3\}\$", "O₃", text, flags=re.IGNORECASE)
    text = re.sub(r"\$\\text\{SO\}\_?\{?2\}?\$|\$\\text\{SO2\}\$", "SO₂", text, flags=re.IGNORECASE)
    text = re.sub(r"\$\\text\{CO\}\$", "CO", text, flags=re.IGNORECASE)
    text = re.sub(r"\$\\text\{CO\}\_?\{?2\}?\$|\$\\text\{CO2\}\$", "CO₂", text, flags=re.IGNORECASE)

    # 2. Units (µg/m³, ppb, ppm)
    text = re.sub(r"\$\\\\mu\\text\{g/m\}\^\{?3\}?\$|\$\\mu\\text\{g/m\}\^\{?3\}?\$", "µg/m³", text)
    text = re.sub(r"\$\\\\mu\\text\{g\}/\\text\{m\}\^\{?3\}?\$|\$\\mu\\text\{g\}/\\text\{m\}\^\{?3\}?\$", "µg/m³", text)
    text = re.sub(r"\$\\mu\s*g/m\^?3\$|\\mu\s*g/m\^?3", "µg/m³", text, flags=re.IGNORECASE)
    text = re.sub(r"\\mu\s*g", "µg", text)

    # 3. Numeric LaTeX units: $102.0\text{ ppb}$ -> 102.0 ppb
    text = re.sub(r"\$([0-9\.\s\-]+)\\text\{([^}]+)\}\$", r"\1 \2", text)
    text = re.sub(r"\$([0-9\.\s\-]+)\s*\\mu\s*g/m\^?3\$", r"\1 µg/m³", text)

    # 4. Generic \text{...} wrappers
    text = re.sub(r"\$\\text\{([^}]+)\}\$", r"\1", text)
    text = re.sub(r"\\text\{([^}]+)\}", r"\1", text)

    # 5. Clean remaining inline math dollar signs around plain text/numbers: $85\text{ (Moderate)}$ -> 85 (Moderate)
    text = re.sub(r"\$([^\$]+)\$", r"\1", text)

    # 6. Normalize Unicode subscripts
    text = re.sub(r"\bPM_2\.5\b", "PM2.5", text)
    text = re.sub(r"\bPM_10\b", "PM10", text)
    text = re.sub(r"\bNO_2\b", "NO₂", text)
    text = re.sub(r"\bO_3\b", "O₃", text)
    text = re.sub(r"\bSO_2\b", "SO₂", text)
    text = re.sub(r"\bCO_2\b", "CO₂", text)

    return text


def get_aqi_category(aqi: int) -> str:
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Unhealthy for Sensitive Groups"
    elif aqi <= 200:
        return "Unhealthy"
    elif aqi <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"


def extract_global_city(query: str) -> Optional[str]:
    """
    Extracts a candidate world city from user message.
    Supports acronyms like 'LA', 'NYC', 'SF', 'KL', 'HK' and full world city names.
    """
    q_lower = query.lower().strip()

    # 1. Check acronym / alias dictionary with word boundaries
    for alias, full_city in CITY_ALIASES.items():
        pattern = r"\b" + re.escape(alias) + r"\b"
        if re.search(pattern, q_lower):
            return full_city

    # If purely asking about Sri Lanka / current local view without a foreign city, skip
    local_indicators = ["kandy", "colombo", "sri lanka", "ceylon", "island", "our city", "this city", "here"]
    if any(loc in q_lower for loc in local_indicators) and not any(gc in q_lower for gc in MAJOR_GLOBAL_CITIES):
        return None

    # 2. Match against known major world cities
    for city in MAJOR_GLOBAL_CITIES:
        pattern = r"\b" + re.escape(city) + r"\b"
        if re.search(pattern, q_lower):
            return city

    # 3. Match conversational query patterns: "in <City>", "for <City>", "aqi of <City>"
    match = re.search(r"(?:in|for|at|of|about)\s+([a-zA-Z\s]{3,25})(?:\?|\.|\s+today|\s+now|\s+aqi|\s+weather|\s+air|$)", q_lower)
    if match:
        candidate = match.group(1).strip()
        if candidate not in ["kandy", "colombo", "sri lanka", "the city", "my city", "this place", "here", "outside", "today", "tomorrow"]:
            return candidate

    return None


def fetch_live_global_aqi(city_query: str) -> Optional[Dict]:
    """
    Fetches real-time live air quality telemetry and meteorological metrics
    for any global city worldwide using Open-Meteo Geocoding & Air Quality APIs.
    """
    try:
        encoded = urllib.parse.quote(city_query.strip())
        geo_url = f"https://geocoding-api.open-meteo.com/v1/search?name={encoded}&count=1&language=en&format=json"
        req_geo = urllib.request.Request(geo_url, headers={"User-Agent": "SentinelAQ-GlobalFetcher/2.0"})
        with urllib.request.urlopen(req_geo, timeout=4) as res_geo:
            geo_data = json.loads(res_geo.read().decode("utf-8"))
            if not geo_data.get("results"):
                return None
            place = geo_data["results"][0]
            lat = place["latitude"]
            lon = place["longitude"]
            official_name = place.get("name", city_query.capitalize())
            country = place.get("country", "")
            admin = place.get("admin1", "")

        aqi_url = f"https://air-quality-api.open-meteo.com/v1/air-quality?latitude={lat}&longitude={lon}&current=us_aqi,pm2_5,pm10,nitrogen_dioxide,ozone,carbon_monoxide"
        req_aqi = urllib.request.Request(aqi_url, headers={"User-Agent": "SentinelAQ-GlobalFetcher/2.0"})
        with urllib.request.urlopen(req_aqi, timeout=4) as res_aqi:
            aqi_data = json.loads(res_aqi.read().decode("utf-8"))
            curr = aqi_data.get("current", {})
            us_aqi = int(curr.get("us_aqi") or 0)
            status = get_aqi_category(us_aqi)

            return {
                "city": official_name,
                "admin": admin,
                "country": country,
                "lat": lat,
                "lon": lon,
                "aqi": us_aqi,
                "status": status,
                "pm25": round(float(curr.get("pm2_5") or 0), 1),
                "pm10": round(float(curr.get("pm10") or 0), 1),
                "no2": round(float(curr.get("nitrogen_dioxide") or 0), 1),
                "o3": round(float(curr.get("ozone") or 0), 1),
                "co": round(float(curr.get("carbon_monoxide") or 0), 1)
            }
    except Exception as e:
        print(f"[SentinelAI] Global telemetry fetch error for '{city_query}': {e}")
        return None


def build_system_prompt(telemetry: Dict, city: str, lang: str, global_telemetry: Optional[Dict] = None) -> str:
    """
    Constructs the system prompt injecting real-time IoT and AI forecast telemetry.
    """
    current_aqi = telemetry.get("aqi", 45)
    status = telemetry.get("status", "Good")
    temp = telemetry.get("temp", "28°C")
    humidity = telemetry.get("humidity", "75%")
    wind = telemetry.get("wind", "12")
    wind_dir = telemetry.get("windDir", 225)
    pm25 = telemetry.get("pm25", {}).get("value", 12.0)
    no2 = telemetry.get("no2", {}).get("value", 10.0)
    o3 = telemetry.get("o3", {}).get("value", 20.0)
    co = telemetry.get("co", {}).get("value", 300.0)
    shap = telemetry.get("shap", {})
    forecasts = telemetry.get("forecasts", [])

    # Best & Peak forecast windows
    future = [f for f in forecasts if f.get("horizon", 0) > 0]
    best_str = "Tomorrow morning"
    peak_str = "Evening rush hour"
    if future:
        min_f = min(future, key=lambda x: x.get("aqi", 999))
        max_f = max(future, key=lambda x: x.get("aqi", 0))
        best_str = f"+{min_f.get('horizon')}h window (Est. AQI {min_f.get('aqi')})"
        peak_str = f"+{max_f.get('horizon')}h window (Est. AQI {max_f.get('aqi')})"

    shap_str = f"Humidity: {shap.get('humidity', '0%')}, Wind: {shap.get('wind', '0%')}, Temp: {shap.get('temp', '0%')}, Topography: {shap.get('topo', '0%')}"

    lang_instructions = {
        "si": "Respond naturally and fluently in Sinhala (සිංහල). Use clear everyday language that ordinary Sri Lankan citizens understand.",
        "ta": "Respond naturally and fluently in Tamil (தமிழ்). Use clear everyday language that ordinary Sri Lankan citizens understand.",
        "en": "Respond in English. Use clear, engaging, non-technical language."
    }.get(lang, "Respond in the same language as the user's message.")

    global_section = ""
    if global_telemetry:
        g_city = global_telemetry.get("city", "Global City")
        g_country = global_telemetry.get("country", "")
        g_admin = global_telemetry.get("admin", "")
        loc_label = f"{g_city}, {g_admin} ({g_country})" if g_admin else f"{g_city} ({g_country})"
        global_section = f"""
================================================================================
LIVE REAL-TIME GLOBAL TELEMETRY RETRIEVED FOR {loc_label.upper()}:
- Current US AQI: {global_telemetry.get('aqi')} ({global_telemetry.get('status')})
- Fine Particulate Matter (PM2.5): {global_telemetry.get('pm25')} µg/m³
- Coarse Particulates (PM10): {global_telemetry.get('pm10')} µg/m³
- Nitrogen Dioxide (NO2): {global_telemetry.get('no2')} ppb
- Ground-Level Ozone (O3): {global_telemetry.get('o3')} ppb
- Carbon Monoxide (CO): {global_telemetry.get('co')} ppb

SPECIAL INSTRUCTION FOR {g_city.upper()}:
- The user is inquiring about {g_city}. State the EXACT live AQI reading ({global_telemetry.get('aqi')} - {global_telemetry.get('status')}) and dominant pollutants right at the start of your response!
- Provide actionable outdoor health advice for residents/travelers in {g_city} right now based on this exact live data.
- Contrast with WHO safety limits or Sri Lanka's microclimates if relevant.
================================================================================
"""

    prompt = f"""You are SentinelAI, an intelligent, empathetic environmental health, atmospheric science, and air quality assistant for the SentinelAQ platform.

CURRENT REAL-TIME TELEMETRY FOR {city.upper()} DISTRICT (SRI LANKA):
- Current AQI: {current_aqi} ({status})
- Dominant Pollutant (PM2.5): {pm25} µg/m³
- Other Gases: NO2: {no2} ppb, Ozone (O3): {o3} ppb, Carbon Monoxide: {co} ppb
- Microclimate: Temperature {temp}, Humidity {humidity}, Wind {wind} km/h (Bearing: {wind_dir}°)
- 24-Hour Predictive BiLSTM Forecast:
  * Cleanest Window: {best_str}
  * Expected Pollution Peak: {peak_str}
- Real-time TreeSHAP Drivers: {shap_str}
{global_section}
CRITICAL FORMATTING INSTRUCTIONS:
1. NEVER USE LATEX MATH NOTATION OR DOLLAR SIGNS. Do NOT write LaTeX math blocks, dollar signs, or backslashes.
2. ALWAYS write clean, standard plain text with Unicode subscripts: PM2.5, PM10, NO₂, O₃, SO₂, CO, µg/m³, ppb, ppm, °C.
3. Use clean bold markdown (e.g. **85 (Moderate)**, **NO₂: 31.8 ppb**, **O₃: 102 ppb**) for readability.

CORE ADVISORY INSTRUCTIONS:
1. When asked about Sri Lanka or the current district ({city.upper()}), ground your answers directly in the real-time sensor readings, TreeSHAP weather factors, and 24h BiLSTM forecast windows above.
2. COMPARISON & TRAVEL ADVISORY RULE:
   - Colombo vs Kandy Dynamics: Colombo is a coastal plain (~5m elevation) where daytime ocean sea breezes disperse smog, while Kandy is an inter-mountain basin (~500m elevation) prone to nocturnal thermal inversion and moisture trapping.
   - Inter-District Travel Health Advisory: If AQI in either district is 50+ (Moderate, Unhealthy for Sensitive Groups, or Hazardous), clearly advise sensitive travelers, asthmatics, respiratory patients, and children to limit non-essential travel into that district or wear a high-filtration protective mask during outdoor transit.
3. When asked about any global city or international air quality: Use the LIVE global telemetry provided above to give the EXACT live AQI, PM2.5, and health guidance!
4. When asked general environmental science, chemistry, or health questions (e.g. "What is PM2.5?", "How do masks work?", "Why does rain clear smog?"), give clear, engaging, easy-to-understand explanations.
5. Keep answers concise, warm, and well-structured with short paragraphs and bullet points.
6. {lang_instructions}
"""
    return prompt


def generate_gemini_response(api_key: str, system_prompt: str, user_message: str, history: Optional[List[Dict]] = None) -> str:
    """
    Calls Google Gemini REST API across available model versions.
    """
    contents = []
    
    # System instruction (or prime message)
    contents.append({
        "role": "user",
        "parts": [{"text": f"System Instructions:\n{system_prompt}\n\nPlease acknowledge and wait for my questions."}]
    })
    contents.append({
        "role": "model",
        "parts": [{"text": "Understood. I am SentinelAI, ready to assist with real-time air quality and health guidance grounded in live SentinelAQ and global atmospheric telemetry."}]
    })

    # Append conversation history
    if history:
        for msg in history[-6:]:  # Keep last 3 turns
            role = "user" if msg.get("role") == "user" else "model"
            contents.append({
                "role": role,
                "parts": [{"text": msg.get("content", "")}]
            })

    # Current user message
    contents.append({
        "role": "user",
        "parts": [{"text": user_message}]
    })

    payload = {
        "contents": contents,
        "generationConfig": {
            "temperature": 0.4,
            "maxOutputTokens": 1500,
            "topP": 0.95
        }
    }

    last_error = None
    for model_name in GEMINI_MODELS:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "x-goog-api-key": api_key
            }
        )

        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                res_data = json.loads(response.read().decode("utf-8"))
                candidates = res_data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        raw_text = parts[0].get("text", "").strip()
                        return clean_latex_formatting(raw_text)
        except urllib.error.HTTPError as e:
            last_error = f"HTTP {e.code} on {model_name}: {e.read().decode('utf-8')}"
            continue
        except Exception as e:
            last_error = str(e)
            continue

    raise RuntimeError(f"All Gemini models failed. Last error: {last_error}")


def fallback_rule_based_response(user_message: str, telemetry: Dict, city: str, lang: str, global_telemetry: Optional[Dict] = None) -> str:
    """
    Intelligent fallback response generator when Gemini API is unreachable or offline.
    """
    current_aqi = telemetry.get("aqi", 45)
    status = telemetry.get("status", "Good")
    temp = telemetry.get("temp", "28°C")
    humidity = telemetry.get("humidity", "75%")
    wind = telemetry.get("wind", "12")
    msg_lower = user_message.lower()

    # 1. Live Global City Response
    if global_telemetry:
        g_city = global_telemetry.get("city", "Global City")
        g_country = global_telemetry.get("country", "")
        g_aqi = global_telemetry.get("aqi", 50)
        g_status = global_telemetry.get("status", "Good")
        g_pm25 = global_telemetry.get("pm25", 0.0)
        g_no2 = global_telemetry.get("no2", 0.0)
        g_o3 = global_telemetry.get("o3", 0.0)
        loc_str = f"{g_city}, {g_country}" if g_country else g_city

        if lang == "si":
            return clean_latex_formatting(
                f"🌍 **සජීවී ගෝලීය වායු තත්ත්ව වාර්තාව — {loc_str}:**\n\n"
                f"• **වත්මන් සජීවී AQI අගය:** **{g_aqi} ({g_status})**\n"
                f"• **සියුම් අංශු (PM2.5):** {g_pm25} µg/m³\n"
                f"• **වායු සංයුතිය:** NO₂: {g_no2} ppb | Ozone (O₃): {g_o3} ppb\n\n"
                f"💡 **සෞඛ්‍ය උපදෙස්:** {g_city} හි වත්මන් වායු තත්ත්වය '{g_status}' මට්ටමේ පවතී. "
                f"{'එළිමහන් කටයුතු ආරක්ෂිතයි.' if g_aqi <= 50 else 'ඇදුම සහ ශ්වසන අපහසුතා ඇති පුද්ගලයින් දිගු වේලාවක් පිටත රැඳී සිටීමෙන් වළකින්න.'}"
            )
        elif lang == "ta":
            return clean_latex_formatting(
                f"🌍 **நேரடி உலகளாவிய காற்று தர அறிக்கை — {loc_str}:**\n\n"
                f"• **தற்போதைய AQI:** **{g_aqi} ({g_status})**\n"
                f"• **PM2.5 துகள்கள்:** {g_pm25} µg/m³\n"
                f"• **வாயுக்கள்:** NO₂: {g_no2} ppb | ஓசோன்: {g_o3} ppb\n\n"
                f"💡 **சுகாதார வழிகாட்டி:** {g_city} இல் தற்போதைய காற்று தரம் '{g_status}' நிலையில் உள்ளது. "
                f"{'வெளிப்புற நடவடிக்கைகளுக்கு பாதுகாப்பானது.' if g_aqi <= 50 else 'சுவாசப் பிரச்சனை உள்ளவர்கள் நீண்ட நேரம் வெளியே இருப்பதைத் தவிர்க்கவும்.'}"
            )
        else:
            return clean_latex_formatting(
                f"🌍 **Live Air Quality Telemetry — {loc_str}:**\n\n"
                f"• **Current Live AQI:** **{g_aqi}** ({g_status})\n"
                f"• **Dominant PM2.5:** {g_pm25} µg/m³ | **PM10:** {global_telemetry.get('pm10', 0)} µg/m³\n"
                f"• **Trace Pollutants:** NO₂: {g_no2} ppb | Ozone (O₃): {g_o3} ppb\n\n"
                f"### Health & Outdoor Guidance for {g_city}:\n"
                f"• **Air Quality Status:** Currently ranked as **{g_status}** under US EPA air standards.\n"
                f"• **Activity Recommendation:** {'Air quality is ideal for outdoor exercise, jogging, and walking.' if g_aqi <= 50 else 'Sensitive individuals and asthmatics should consider reducing prolonged heavy exertion outdoors.' if g_aqi <= 100 else 'Avoid intense outdoor workouts during peak traffic hours; wear an N95 mask if commuting along major arterial roads.'}\n\n"
                f"*Data dynamically ingested via SentinelAQ Global Atmospheric Telemetry Engine.*"
            )

    # 2. Colombo vs Kandy Comparison & Inter-District Travel Advisory
    if any(term in msg_lower for term in ["compare", "colombo vs kandy", "kandy vs colombo", "travel", "ගමන්", "සසඳ", "ஒப்பீடு", "பயணம்"]):
        is_above_50 = int(current_aqi) > 50
        if lang == "si":
            if is_above_50:
                return (
                    f"⚠️ **දිස්ත්‍රික්ක අතර ගමන් සෞඛ්‍ය අනතුරු ඇඟවීම ({city.capitalize()}):**\n\n"
                    f"වත්මන් AQI අගය **{current_aqi} ({status})** මට්ටමේ පවතී (50 ට වැඩි).\n\n"
                    f"• **සංචාරක උපදෙස්:** ඇදුම රෝගීන්, ළමුන් සහ වැඩිහිටියන් {city.capitalize()} දිස්ත්‍රික්කය වෙත අනවශ්‍ය ගමන් සීමා කළ යුතු අතර, ගමන් කරන්නේ නම් N95 මුහුණු ආවරණයක් පැළඳීම අනිවාර්ය වේ.\n"
                    f"• **නගර සංසන්දනය:** කොළඹ මුහුදු සුළං මඟින් වාතය පිරිසිදු කරන අතර, මහනුවර කඳුකර නිම්න පිහිටීම නිසා රාත්‍රී කාලයේ වායු දූෂක කොටුවීමේ අවදානමක් පවතී."
                )
            else:
                return (
                    f"✅ **නගර සංසන්දනය සහ ගමන් උපදෙස් ({city.capitalize()}):**\n\n"
                    f"වත්මන් AQI අගය **{current_aqi} ({status})** වන අතර එය 50 සීමාවට වඩා අඩු පිරිසිදු මට්ටමක පවතී.\n\n"
                    f"• **ගමන් තත්ත්වය:** දිස්ත්‍රික්ක අතර ගමන් කිරීම සඳහා වායු තත්ත්වය සුදුසුයි.\n"
                    f"• **කාලගුණ සාධක:** කොළඹ දිවාකාලයේ මුහුදු සුළඟින් වායු පිරිසිදු වන අතර, මහනුවර සවස් භාගයේ අධික ආර්ද්‍රතාවය හේතුවෙන් සුළු ඝනත්වයක් ඇති විය හැක."
                )
        elif lang == "ta":
            if is_above_50:
                return (
                    f"⚠️ **மாவட்டங்களுக்கு இடையேயான பயண சுகாதார எச்சரிக்கை ({city.capitalize()}):**\n\n"
                    f"தற்போதைய AQI **{current_aqi} ({status})** (50 க்கும் மேல்).\n\n"
                    f"• **பயண ஆலோசனை:** ஆஸ்துமா உள்ளவர்கள் மற்றும் குழந்தைகள் {city.capitalize()} மாவட்டத்திற்கு தேவையற்ற பயணங்களைத் தவிர்க்கவும் அல்லது முகக்கவசம் அணியவும்.\n"
                    f"• **ஒப்பீடு:** கொழும்பு கடல் காற்றினால் காற்றை சுத்தப்படுத்துகிறது, கண்டி மலைப்பள்ளத்தாக்கு இரவில் புகையை சிக்க வைக்கிறது."
                )
            else:
                return (
                    f"✅ **நகர ஒப்பீடு மற்றும் பயண வழிகாட்டி ({city.capitalize()}):**\n\n"
                    f"தற்போதைய AQI **{current_aqi} ({status})** (50 க்கும் குறைவான சுத்தமான காற்று).\n\n"
                    f"• **பயண நிலை:** மாவட்டங்களுக்கு இடையே பயணம் செய்ய பாதுகாப்பானது."
                )
        else:
            if is_above_50:
                return (
                    f"⚠️ **Inter-District Travel Health Advisory ({city.capitalize()}):**\n\n"
                    f"Current AQI in {city.capitalize()} is **{current_aqi} ({status})** — exceeding the 50 AQI threshold.\n\n"
                    f"• **Travel Guidance:** Asthmatics, respiratory patients, elderly, and children are advised to limit non-essential travel to this district or wear a protective N95 mask during transit.\n"
                    f"• **Microclimate Comparison:** Colombo benefits from oceanic sea breeze dispersion, whereas Kandy's inter-mountain bowl geography traps particulate matter during nocturnal temperature inversions."
                )
            else:
                return (
                    f"✅ **Colombo vs Kandy Comparison & Travel Guidance:**\n\n"
                    f"Current AQI in {city.capitalize()} is **{current_aqi} ({status})** — safely below the 50 AQI advisory limit.\n\n"
                    f"• **Travel Guidance:** Inter-district transit between Western and Central Provinces is currently favorable and safe for all groups.\n"
                    f"• **Microclimate Comparison:**\n"
                    f"  * **Colombo:** Coastal plain (~5m) with active onshore marine breezes cleansing daytime vehicle emissions.\n"
                    f"  * **Kandy:** Inter-mountain valley basin (~500m) with high humidity and nocturnal valley drafts."
                )

    # 3. General Concept Definitions (What is AQI, PM2.5, NO2, etc.)
    if any(term in msg_lower for term in ["what is aqi", "aqi meaning", "explain aqi", "aqi යනු"]):
        return (
            "📊 **What is the Air Quality Index (AQI)?**\n\n"
            "The **AQI** is a standardized scale from 0 to 500 that translates complex chemical concentrations into clear health stages:\n\n"
            "• **0 – 50 (Good):** Air is clean and safe for all.\n"
            "• **51 – 100 (Moderate):** Acceptable quality; very sensitive individuals may experience mild irritation.\n"
            "• **101 – 150 (Unhealthy for Sensitive Groups):** Asthmatics, children, and elderly should reduce heavy outdoor exertion.\n"
            "• **151 – 200 (Unhealthy):** Everyone should consider wearing a mask outdoors."
        )

    if any(term in msg_lower for term in ["pm2.5", "pm25", "particulate"]):
        return (
            "🔬 **What is PM2.5?**\n\n"
            "**PM2.5** refers to microscopic airborne particles smaller than 2.5 micrometers (about 30 times finer than a human hair).\n\n"
            "• **Why it matters:** Because they are so tiny, they penetrate deep into the lungs and bloodstream.\n"
            f"• **Current Reading ({city.capitalize()}):** {telemetry.get('pm25', {}).get('value', 12)} µg/m³."
        )

    # 4. Outdoor Activities / Jogging
    if any(w in msg_lower for w in ["jog", "run", "walk", "outside", "exercise", "sport", "workout", "පිටත", "ඇවිද", "ක්‍රීඩා", "வெளியே", "ஓட"]):
        if lang == "si":
            return (
                f"🏃 **එළිමහන් ක්‍රියාකාරකම් උපදෙස් ({city.capitalize()}):**\n\n"
                f"වත්මන් AQI අගය **{current_aqi} ({status})** වේ. "
                f"දැනට වාතය සාමාන්‍ය මට්ටමක පවතින බැවින් සාමාන්‍ය එළිමහන් කටයුතු ආරක්ෂිතයි.\n\n"
                f"💡 **හොඳම කාලය:** හෙට උදෑසන 6:00 – 8:30 අතර කාලය පිරිසිදු වාතය සඳහා වඩාත් සුදුසු වේ."
            )
        elif lang == "ta":
            return (
                f"🏃 **வெளிப்புற நடவடிக்கை வழிகாட்டி ({city.capitalize()}):**\n\n"
                f"தற்போதைய AQI **{current_aqi} ({status})** ஆகும். "
                f"பொதுவான வெளிப்புற நடவடிக்கைகளுக்கு பாதுகாப்பானது.\n\n"
                f"💡 **சிறந்த நேரம்:** நாளை காலை 6:00 – 8:30 வரை சுத்தமான காற்று இருக்கும்."
            )
        else:
            return (
                f"🏃 **Outdoor Activity Guidance for {city.capitalize()}:**\n\n"
                f"Current AQI is **{current_aqi} ({status})** with PM2.5 at **{telemetry.get('pm25', {}).get('value', 12)} µg/m³**.\n\n"
                f"• **Best Window:** Morning hours (6:00 AM – 9:00 AM) offer the cleanest air window.\n"
                f"• **Caution Window:** Limit strenuous cardio during evening rush hour (6:00 PM – 9:00 PM) when humidity traps traffic emissions."
            )

    # 5. Weather / SHAP Drivers
    if any(w in msg_lower for w in ["why", "cause", "factor", "reason", "humidity", "wind", "spike", "ඇයි", "හේතුව", "காரணம்"]):
        if lang == "si":
            return (
                f"🔍 **වායු තත්ත්ව සාධක විශ්ලේෂණය ({city.capitalize()}):**\n\n"
                f"වත්මන් ආර්ද්‍රතාවය **{humidity}** වන අතර සුළඟ පැයට කි.මී. **{wind}** කි. "
                f"ආර්ද්‍රතාවය ඉහළ යාම නිසා සියුම් දූවිලි අංශු පහළ මට්ටමේ රැඳී පවතී."
            )
        elif lang == "ta":
            return (
                f"🔍 **காற்று காரணிகள் அறிக்கை ({city.capitalize()}):**\n\n"
                f"ஈரப்பதம் **{humidity}**, காற்று வேகம் **{wind} km/h**.\n\n"
                f"அதிக ஈரப்பதம் நுண்ணிய துகள்களை தரையிலேயே தக்கவைக்கிறது."
            )
        else:
            return (
                f"🔍 **Environmental Factor Breakdown for {city.capitalize()}:**\n\n"
                f"Current conditions: Humidity at **{humidity}**, Wind at **{wind} km/h**.\n\n"
                f"• **Humidity & Moisture:** High humidity causes microscopic PM2.5 particles to swell with moisture, keeping them suspended near ground level.\n"
                f"• **Ventilation:** Active breezes help flush out pollution, while stagnant periods let vehicle exhaust accumulate."
            )

    # 6. Sensitive Groups / Health
    if any(w in msg_lower for w in ["child", "asthma", "elderly", "mask", "safe", "health", "sensitive", "ළමුන්", "ඇදුම", "குழந்தை", "ஆஸ்துமா"]):
        if lang == "si":
            return (
                f"🫁 **සෞඛ්‍ය හා සංවේදී කණ්ඩායම් උපදෙස් ({city.capitalize()}):**\n\n"
                f"වත්මන් AQI අගය **{current_aqi} ({status})** වේ.\n\n"
                f"• **සාමාන්‍ය ජනතාව:** එදිනෙදා කටයුතු සඳහා ආරක්ෂිතයි.\n"
                f"• **ඇදුම රෝගීන් සහ ළමුන්:** සවස් කාලයේ වායු ඝනත්වය වැඩි වුවහොත් මුහුණු ආවරණ පළඳින්න."
            )
        else:
            return (
                f"🫁 **Health & Sensitive Groups Advisory for {city.capitalize()}:**\n\n"
                f"Current AQI is **{current_aqi} ({status})**.\n\n"
                f"• **General Public:** Safe for regular everyday activities.\n"
                f"• **Asthmatics & Children:** If AQI rises above 100 during evening inversion, wear a standard protective mask outdoors and keep inhalers accessible."
            )

    # 7. Default City Telemetry Summary
    if lang == "si":
        return (
            f"🌿 **SentinelAI සජීවී වායු වාර්තාව ({city.capitalize()}):**\n\n"
            f"• වත්මන් AQI: **{current_aqi} ({status})**\n"
            f"• උෂ්ණත්වය: **{temp}** | ආර්ද්‍රතාව: **{humidity}** | සුළඟ: **{wind} km/h**\n\n"
            f"ඔබට එළිමහන් කටයුතු, මුහුණු ආවරණ හෝ අනාවැකි පිළිබඳ ඕනෑම ප්‍රශ්නයක් විමසිය හැක."
        )
    elif lang == "ta":
        return (
            f"🌿 **SentinelAI நேரடி காற்று அறிக்கை ({city.capitalize()}):**\n\n"
            f"• தற்போதைய AQI: **{current_aqi} ({status})**\n"
            f"• வெப்பநிலை: **{temp}** | ஈரப்பதம்: **{humidity}** | காற்று: **{wind} km/h**\n\n"
            f"வெளிப்புற பயிற்சிகள், ஜன்னல் பாதுகாப்பு அல்லது முன்னறிவிப்பு பற்றி நீங்கள் கேட்கலாம்."
        )
    else:
        return (
            f"🌿 **SentinelAI Live Air Quality Summary for {city.capitalize()}:**\n\n"
            f"• **Current AQI:** {current_aqi} ({status})\n"
            f"• **PM2.5:** {telemetry.get('pm25', {}).get('value', 12)} µg/m³ | **NO2:** {telemetry.get('no2', {}).get('value', 10)} ppb\n"
            f"• **Weather:** {temp}, {humidity} humidity, {wind} km/h wind.\n\n"
            f"Feel free to ask about outdoor exercise timings, health precautions, or 24-hour forecast trends!"
        )


def _load_env_fallback():
    for env_path in [".env", "backend/.env", "../.env", "/root/aqi-backend/backend/.env"]:
        if os.path.exists(env_path):
            try:
                with open(env_path, "r", encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#") and "=" in line:
                            k, v = line.split("=", 1)
                            k = k.strip()
                            v = v.strip().strip('"').strip("'")
                            if k and k not in os.environ:
                                os.environ[k] = v
            except Exception:
                pass


def answer_user_query(user_message: str, telemetry: Dict, city: str = "kandy", lang: str = "en", history: Optional[List[Dict]] = None) -> Dict:
    """
    Main entry point for conversational air quality queries.
    Dynamically ingests global atmospheric telemetry for world cities.
    Tries Google Gemini LLM first; gracefully falls back to intelligent rule-based engine.
    """
    # 1. Check if user is asking about an international/global world city (including acronyms like LA, NYC, SF)
    global_telemetry = None
    target_city = extract_global_city(user_message)
    if target_city:
        global_telemetry = fetch_live_global_aqi(target_city)

    # 2. Read API Key from environment variable (or .env fallback)
    _load_env_fallback()
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")

    if api_key and len(api_key.strip()) > 10:
        try:
            system_prompt = build_system_prompt(telemetry, city, lang, global_telemetry)
            reply_text = generate_gemini_response(api_key.strip(), system_prompt, user_message, history)
            return {
                "source": "gemini_llm",
                "city": city,
                "lang": lang,
                "global_data": global_telemetry,
                "reply": clean_latex_formatting(reply_text)
            }
        except Exception as e:
            print(f"[SentinelAI] Gemini API error: {e}. Falling back to rule-based engine.")

    # 3. Rule-based fallback (with real-time global telemetry if available)
    reply_text = fallback_rule_based_response(user_message, telemetry, city, lang, global_telemetry)
    return {
        "source": "sentinel_ai_engine",
        "city": city,
        "lang": lang,
        "global_data": global_telemetry,
        "reply": clean_latex_formatting(reply_text)
    }
