/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#513300",
        "primary-fixed-dim": "#82cfff",
        "on-surface-variant": "#3e4850",
        "tertiary-fixed-dim": "#ffb953",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#00aeef",
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f4",
        "on-secondary-container": "#457000",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#82cfff",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "outline": "#6e7881",
        "on-secondary-fixed-variant": "#304f00",
        "tertiary-container": "#db951f",
        "primary-fixed": "#c6e7ff",
        "surface": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "on-primary-container": "#003e58",
        "on-background": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "surface-container": "#eeeeee",
        "outline-variant": "#bdc8d1",
        "on-secondary": "#ffffff",
        "surface-tint": "#00658d",
        "on-tertiary-fixed-variant": "#633f00",
        "surface-container-high": "#e8e8e8",
        "tertiary": "#825500",
        "surface-variant": "#e2e2e2",
        "background": "#f9f9f9",
        "secondary-fixed": "#b7f568",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#102000",
        "tertiary-fixed": "#ffddb4",
        "primary": "#00658d",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-fixed-variant": "#004c6b",
        "secondary-fixed-dim": "#9cd84f",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#291800",
        "secondary": "#416900",
        "on-primary-fixed": "#001e2d",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "secondary-container": "#b7f568",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "glass-margin": "12px",
        "container-padding": "24px",
        "element-gap": "16px",
        "desktop-max-width": "1200px",
      },
      fontFamily: {
        "display-aqi": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Fira Sans"],
        "label-caps": ["Fira Sans"],
      },
      fontSize: {
        "display-aqi": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
