import React from 'react'
import { useLanguage } from '../context/LanguageContext'

export default function TrendsExplainerModal({ isOpen, onClose }) {
  const { t, lang } = useLanguage()

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-[9990] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-[fadeIn_0.2s_ease-out]">
      <div
        className="relative w-full max-w-sm bg-gradient-to-b from-[#eaf4f7] via-[#f7faf9] to-[#f0f5f4] rounded-3xl p-6 shadow-2xl border border-white/80 overflow-hidden max-h-[88vh] overflow-y-auto"
        style={{
          fontFamily:
            lang === 'si'
              ? "'Noto Sans Sinhala', sans-serif"
              : lang === 'ta'
              ? "'Noto Sans Tamil', sans-serif"
              : 'inherit',
        }}
      >
        {/* Top Ambient Glow */}
        <div className="absolute top-0 right-0 w-36 h-36 bg-[#00658d]/10 rounded-full blur-2xl -mr-10 -mt-10 pointer-events-none" />

        {/* Modal Header */}
        <div className="flex justify-between items-start mb-4 relative z-10">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-[#004c6b]/10 flex items-center justify-center text-[#004c6b]">
              <span className="material-symbols-outlined text-[20px]">show_chart</span>
            </div>
            <div>
              <h3 className="text-base font-extrabold text-[#003e58] leading-tight">
                {t('trendsModalTitle') || 'Understanding Forecasts & Trends'}
              </h3>
              <p className="text-[11px] font-semibold text-[#52798e]">
                {t('trendsModalSubtitle') || 'How to read the predictive timeline'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close modal"
            className="w-8 h-8 rounded-full bg-black/5 hover:bg-black/10 active:scale-90 flex items-center justify-center text-[#3e5b6e] transition-all"
          >
            <span className="material-symbols-outlined text-base">close</span>
          </button>
        </div>

        {/* Section 1: The 24-Hour Horizon Line */}
        <div className="bg-white/80 backdrop-blur-md rounded-2xl p-4 border border-black/5 shadow-sm mb-4 relative z-10">
          <h4 className="text-xs font-black text-[#004c6b] uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[15px]">timeline</span>
            {t('trendLineGuideTitle') || 'The 2-Part Timeline Graph'}
          </h4>

          <div className="space-y-2.5 text-xs text-[#2a383f]">
            <div className="flex items-start gap-2 bg-[#f0f6f8] p-2.5 rounded-xl border border-black/5">
              <span className="w-3 h-3 rounded-full bg-[#1b5e7d] shrink-0 mt-0.5" />
              <div>
                <strong className="text-[#004c6b] block font-bold">
                  {t('past24h') || 'Past 24 Hours'} (Solid Blue Line)
                </strong>
                <span className="text-[11px] text-[#475569] leading-snug">
                  {t('past24hExplanation') ||
                    'Real telemetry recorded by ground IoT stations over the past 24 hours.'}
                </span>
              </div>
            </div>

            <div className="flex items-start gap-2 bg-[#fffbeb] p-2.5 rounded-xl border border-amber-200">
              <span className="w-3 h-3 rounded-full border-2 border-[#db951f] shrink-0 mt-0.5" />
              <div>
                <strong className="text-amber-900 block font-bold">
                  {t('forecast') || 'Next 24 Hours'} (Dashed Gold Line)
                </strong>
                <span className="text-[11px] text-[#78350f] leading-snug">
                  {t('forecastExplanation') ||
                    'Predictive trajectory generated by the deep learning BiLSTM-Attention model.'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: Uncertainty Corridor / Prediction Range */}
        <div className="bg-white/80 backdrop-blur-md rounded-2xl p-4 border border-black/5 shadow-sm mb-4 relative z-10">
          <h4 className="text-xs font-black text-[#004c6b] uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[15px]">area_chart</span>
            {t('corridorGuideTitle') || 'Shaded Prediction Range'}
          </h4>
          <p className="text-xs text-[#2a383f] leading-relaxed mb-2">
            {t('corridorGuideBody') ||
              'The soft shaded area around the forecast represents the expected atmospheric range. Near-term hours have high certainty, while later hours show natural meteorological fluctuations.'}
          </p>
          <div className="flex items-center gap-2 bg-[#f0f7f4] px-3 py-1.5 rounded-xl border border-black/5 text-[11px] font-semibold text-[#004c6b]">
            <span className="material-symbols-outlined text-[14px]">touch_app</span>
            <span>{t('interactiveScrubHint') || 'Tip: Drag your finger along the chart to inspect any hour.'}</span>
          </div>
        </div>

        {/* Section 3: Historical Analysis Slider */}
        <div className="bg-white/80 backdrop-blur-md rounded-2xl p-4 border border-black/5 shadow-sm mb-5 relative z-10">
          <h4 className="text-xs font-black text-[#004c6b] uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[15px]">tune</span>
            {t('sliderGuideTitle') || 'Historical Timeline Slider'}
          </h4>
          <ul className="text-[11px] text-[#334155] space-y-1.5 pl-2 leading-relaxed">
            <li>
              <strong className="text-[#004c6b]">Hourly:</strong>{' '}
              {t('hourlySliderDesc') || 'Hour-by-hour sensor observations over the past 24 hours.'}
            </li>
            <li>
              <strong className="text-[#004c6b]">Weekly:</strong>{' '}
              {t('weeklySliderDesc') || 'Daily average AQI trends across the past 7 days.'}
            </li>
            <li>
              <strong className="text-[#004c6b]">Monthly:</strong>{' '}
              {t('monthlySliderDesc') || '30-day historical progression showing seasonal patterns.'}
            </li>
          </ul>
        </div>

        {/* Action Button */}
        <button
          onClick={onClose}
          className="w-full py-3 bg-[#004c6b] hover:bg-[#003850] active:scale-[0.98] text-white rounded-2xl font-bold text-xs shadow-md transition-all flex items-center justify-center gap-1.5 relative z-10"
        >
          <span className="material-symbols-outlined text-base">check</span>
          <span>{t('dismissModal') || 'Got it'}</span>
        </button>
      </div>
    </div>
  )
}
